In [8]:
def fat(n):
    if n <= 1:
        return 1
    else:
        return n*fat(n-1)

In [4]:
import numpy as np
grade_1 = np.array(
    [[8,6,0,0,9,3,0,1,0],
     [0,9,5,0,0,4,0,6,2],
     [0,0,7,2,0,8,0,9,5],
     [0,0,3,9,2,0,7,4,0],
     [7,0,4,6,8,0,5,0,0],
     [1,5,0,0,4,0,2,0,6],
     [0,4,0,1,7,6,9,0,0],
     [9,0,0,8,0,2,0,0,4],
     [5,7,1,0,0,0,6,2,8]])
grade_2 =np.array(
    [[5,3,0,0,7,0,0,0,0],
     [6,0,0,1,9,5,0,0,0],
     [0,9,8,0,0,0,0,6,0],
     [8,0,0,0,6,0,0,0,3],
     [4,0,0,8,0,3,0,0,1],
     [7,0,0,0,2,0,0,0,6],
     [0,6,0,0,0,0,2,8,0],
     [0,0,0,4,1,9,0,0,5],
     [0,0,0,0,8,0,0,7,9]])

In [5]:
def possivel(grade, y, x, n):
    #grade[linha][coluna]
    #É possível colocar n na linha 'y', coluna 'x' da grade?
    #testo a linha
    for i in range(9):
        if grade[y][i] == n:
            return False
    #testar a coluna
    for i in range(9):
        if grade[i][x] == n:
            return False
    #verifico a Caixa
    x0 = (x//3) * 3
    y0 = (y//3) * 3
    for i in range(3):
        for j in range(3):
            if grade[y0 + i][x0 + j] == n:
                return False
    return True    

In [10]:
def solve(grade):
    for i in range(9):
        for j in range(9):
            if grade[i][j] == 0:
                for n in range(1,10):
                    if possivel(grade, i, j, n):
                        grade[i][j] = n
                        solve(grade)
                        grade[i][j] = 0
                return    
    print(grade)
    input('q ota')

In [ ]:
solve(grade_2)

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
